import asyncio
import fitz  # PyMuPDF
from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.conditions import MaxMessageTermination, TextMentionTermination
from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.ui import Console
from autogen_ext.models.openai import OpenAIChatCompletionClient

# --- PROMPT from external source ---
SPECIALIST_PROMPT = """
You are an expert medical analyst with comprehensive knowledge of laboratory medicine, hematology, and gastroenterology. 

When analyzing a new blood report, consider:

1. Complete Blood Count (CBC)
   - Anemia, Polycythemia
   - Leukemia, Infections
   - Thrombocytopenia, Thrombocytosis

2. Liver function tests (ALT, AST, ALP, Bilirubin)
   - Hepatitis
   - Cirrhosis
   - Fatty Liver Disease
   - Cholestasis

3. Pancreatic markers (Amylase, Lipase)
   - Pancreatitis
   - Pancreatic Cancer

4. Metabolic Panel
   - Diabetes
   - Kidney Disease
   - Electrolyte Imbalances

5. Lipid Profile
   - Hyperlipidemia
   - Atherosclerosis
   - Metabolic Syndrome

6. Common Infections & Diseases
   - Bacterial Infections
   - Viral Infections
   - Thyroid Disorders
   - Autoimmune Conditions
   - Nutritional Deficiencies
   - Allergies
   - Inflammatory Conditions

Based on the provided blood report, provide a single comprehensive analysis in the following format:

> **Disclaimer**: This analysis is generated by AI and should not be considered as a replacement for professional medical advice. Please consult with a healthcare provider for proper medical diagnosis and treatment.

### AI Generated Diagnosis:

- **Potential Health Risks:**
  - [List specific conditions the patient might be at risk for]
  - [Include risk level: Low/Medium/High]
  - [Supporting evidence from blood values]

- **Recommendations:**
  - [Lifestyle modifications needed]
  - [Dietary recommendations]
  - [Follow-up tests required]
  - [Preventive measures]
  - [Urgency of medical consultation if needed]

Note: Focus on early detection and prevention. Explain how current blood values might indicate future health risks and what can be done to prevent them.
"""

# --- PDF Reader ---
def extract_text_from_pdf(file_path: str) -> str:
    """Extract all text from the given PDF using PyMuPDF."""
    text = ""
    with fitz.open(file_path) as doc:
        for page in doc:
            text += page.get_text()
    return text

# --- Main async logic ---
async def main():
    model_client = OpenAIChatCompletionClient(model="gpt-4o-2024-11-20")

    termination = MaxMessageTermination(max_messages=10) | TextMentionTermination("TERMINATE")

    assistant = AssistantAgent(
        "assistant",
        model_client=model_client,
        system_message=SPECIALIST_PROMPT
    )

    critic_agent = AssistantAgent(
        "critic",
        model_client=model_client,
        system_message=(
            "You are a critical reviewer of medical analyses. Always provide detailed suggestions, regardless of quality. "
             "Focus on clarity, completeness, potential risks, or edge cases the assistant might have missed. Do not respond with only 'TERMINATE'."
             )
        )


    team = RoundRobinGroupChat(
        participants=[assistant, critic_agent],
        termination_condition=termination
    )

    # Load PDF text
    file_path = "lab_test.pdf"  # Change to your uploaded filename
    report_text = extract_text_from_pdf(file_path)

    # Construct prompt task
    task = (
        "A patient uploaded a blood test report. Based on the report contents, please provide your interpretation "
        "and generate a comprehensive diagnosis and personalized recommendations. "
        "Do not repeat the raw report or lab values in full. Focus on summarizing potential health risks, "
        "diagnostic concerns, and next steps. Follow the format from your system prompt."
        )
    await Console(team.run_stream(task=task))

# --- Run the app ---
asyncio.run(main())